version: '3.7'
services:
  service1:
    image: sboncio/service1
    build: ./service1
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    image: sboncio/service2
    build: ./service2
    command: gunicorn --bind 0.0.0.0:5001 app:app
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    image: sboncio/service3
    build: ./service3
    command: gunicorn --bind 0.0.0.0:5002 app:app
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    image: sboncio/service4
    build: ./service4
    command: gunicorn --bind 0.0.0.0:5003 app:app
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'hannahandsam1'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
    - target: 3306
      published: 3306
    
