- name: 'Allow for packages'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - python3
    state: latest
    update_cache: true
- name: 'Add key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: 'pip installs'
  pip: 
   name: docker-py
    
- name: 'Add repo'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
- name: Update all packages to the latest version
  apt:
    upgrade: dist
- name: 'Download docker'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: true
