- hosts: docker
  become: yes
  roles:
  - role: docker
  - role: compose
- hosts: master
  become: yes
  roles:
  - role: master
- hosts: worker1
  become: yes
  roles:
  - role: worker
    vars:
      token: "{{ hostvars['worker_token']['value']['stdout'] }}"
- hosts: worker2
  become: yes
  roles:
  - role: worker
    vars:
      token: "{{ hostvars['worker_token']['value']['stdout'] }}"
- hosts: docker
  become: yes
  roles:
  - role: nginx-install
  - role: nginx-configure
  - role: nginx-reload
