- name: Leave swarm for a node
  docker_swarm:
    state: absent
    force: true
- name: "Add nodes"
  docker_swarm:
    state: join
    advertise_addr: 35.230.138.49
    join_token: "{{ token['stdout'] }}"
    remote_addrs: [ '35.242.138.143:2377' ]